---
  - name: configure firewall
    hosts: 10.8.22.200
    gather_facts: false
    become: true
    tasks:
      - name: Enable firewalld
        service:
          name: firewalld
          state: started
          enabled: yes
      - name: setting up iptables permanent config
        firewalld:
          service: http
          permanent: true
          state: enabled
      - name: setting up iptables runtime config
        firewalld:
          service: http
          state: enabled
        notify:
        - reload firewalld

    handlers:
      - name: reload firewalld
        service: name=firewalld state=reloaded
