- name: deploy apache
  hosts: 10.8.22.200
  gather_facts: false
  become: true
  ansible_become_method: su
  ansible_become_user: test
  ansible_become_exe: 'sudo -p "Password: " su -'
  tasks:
  - name: install apache
    yum:
      name: httpd
      state: latest
  - name: enable apache at boot
    service:
      name: httpd
      enabled: yes
  - name: start apache
    service:
      name: httpd
      state: started
